## Netlify: skip auto builds unless DEPLOY_ON_DEMAND=1
[build]
  command = "npm run build"
  publish = "dist"

# Build environment
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-fund"
